/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  enascimento
 * Created: 13/11/2018
 */

CREATE SEQUENCE "SEQ_TIPO_SOFTWARE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_COMPUTADOR" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_COMPUTADOR_SOFTWARE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_MARCA" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_SOFTWARE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_IP" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_LICENSE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 19 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_TI_OPEN_LICENSE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 56 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_TI_TIPO_LICENSE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 62 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_RH_TREINAMENTO_QUALIDADE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 148 
NOCACHE 
NOORDER 
CYCLE ;

CREATE SEQUENCE "SEQ_RH_FUNCAO_TREINAMENTO" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1290
NOCACHE 
NOORDER 
CYCLE ;

CREATE SEQUENCE "SEQ_RH_FUNCAO_QUALIDADE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 111
NOCACHE 
NOORDER 
CYCLE ;

CREATE SEQUENCE "SEQ_RH_FUNC_QUAL_SGI" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 201
NOCACHE 
NOORDER 
CYCLE ;






CREATE SEQUENCE "SEQ_CANA_DIA_FRENTE" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;
CREATE SEQUENCE "SEQ_FRENTE_CAPAC_DIARIA" 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
CYCLE ;